# =============================================================================
# Multi-stage Dockerfile for NX monorepo NestJS services
#
# Usage:
#   docker build --build-arg APP=auth-service -t saas/auth-service .
#   docker build --build-arg APP=api-gateway  -t saas/api-gateway  .
#
# Why multi-stage?
#   Stage 1 (builder): full devDeps + NX + TypeScript — heavy, only used to compile
#   Stage 2 (runner):  only the compiled bundle + prod deps — lean final image
#
# Why build context = monorepo root?
#   NX bundles everything (libs/* included) into a single dist/apps/<APP>/main.js
#   via webpack. We only need that file + the .proto files at runtime.
#
# Why is .prisma/<client> at /app/.prisma/ and not node_modules?
#   Webpack externalizes Prisma clients with relative requires:
#     require(".prisma/auth-client")
#   Node resolves ".prisma/..." relative to the requiring file's directory.
#   Since main.js lives at /app/main.js, the client must be at /app/.prisma/.
# =============================================================================

ARG APP
ARG NODE_VERSION=22-alpine

# -----------------------------------------------------------------------------
# Stage 1 — builder
# Installs ALL dependencies and runs `nx build <APP>`
# -----------------------------------------------------------------------------
FROM node:${NODE_VERSION} AS builder

# Build argument must be redeclared after FROM
ARG APP

WORKDIR /workspace

# Install pnpm
RUN corepack enable && corepack prepare pnpm@latest --activate

# Copy dependency manifests first (layer cache — only invalidated on dep changes)
COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./

# Copy all app/lib package.json files so pnpm workspace resolution works
COPY apps/*/package.json* ./apps/
COPY libs/*/package.json* ./libs/

# Install all dependencies (including devDeps needed for the build)
RUN pnpm install --frozen-lockfile

# Copy the full source
COPY . .

# Generate Prisma client if the app has a schema
# The || true prevents failure for apps without Prisma
RUN if [ -f "apps/${APP}/prisma/schema.prisma" ]; then \
      pnpm prisma generate --schema="apps/${APP}/prisma/schema.prisma"; \
    fi

# Build the target app — NX compiles TS + bundles libs into dist/apps/<APP>/main.js
RUN pnpm nx build ${APP} --configuration=production

# -----------------------------------------------------------------------------
# Stage 2 — runner
# Lean production image: compiled bundle + prod deps + proto files
# -----------------------------------------------------------------------------
FROM node:${NODE_VERSION} AS runner

ARG APP
ENV APP=${APP}
ENV NODE_ENV=production

WORKDIR /app

# Install pnpm (needed to install prod deps)
RUN corepack enable && corepack prepare pnpm@latest --activate

# Copy the compiled bundle
COPY --from=builder /workspace/dist/apps/${APP}/main.js ./main.js

# Copy package.json + lockfile (generated by NX with only prod deps)
# and install prod dependencies
COPY --from=builder /workspace/dist/apps/${APP}/package.json ./package.json
COPY --from=builder /workspace/dist/apps/${APP}/pnpm-lock.yaml ./pnpm-lock.yaml
RUN pnpm install --prod --frozen-lockfile --ignore-scripts

# Copy .proto files — gRPC loads them at runtime via protoPath
# GRPC_PROTO_DIR env var points here: /app/libs/grpc/protos
COPY --from=builder /workspace/libs/grpc/protos ./libs/grpc/protos

# Copy Prisma client if it exists (auth-service → .prisma/auth-client, etc.)
# Webpack externalizes these as require(".prisma/auth-client"), which Node
# resolves relative to main.js — so the client must live at /app/.prisma/
#
# The client directory name comes from the schema.prisma `output` field,
# NOT from the app name. Naming convention: <service-name>-client strips "-service"
# e.g. auth-service → auth-client, club-service → club-client
RUN --mount=type=bind,from=builder,source=/workspace/node_modules/.prisma,target=/prisma-clients \
    CLIENT_NAME=$(echo "${APP}" | sed 's/-service$//') && \
    if [ -d "/prisma-clients/${CLIENT_NAME}-client" ]; then \
      mkdir -p /app/.prisma && \
      cp -r "/prisma-clients/${CLIENT_NAME}-client" "/app/.prisma/${CLIENT_NAME}-client"; \
    fi

# Copy Prisma migration files (only exists for auth-service and club-service)
# The entrypoint-migrate.sh script runs `prisma migrate deploy` on startup.
RUN --mount=type=bind,from=builder,source=/workspace,target=/src \
    if [ -d "/src/apps/${APP}/prisma" ]; then \
      cp -r "/src/apps/${APP}/prisma" /app/prisma; \
    fi

# Copy Prisma CLI binary from builder — it's a devDep so not in prod deps.
# entrypoint-migrate.sh calls `npx prisma migrate deploy` which needs the CLI.
COPY --from=builder /workspace/node_modules/.bin/prisma /app/node_modules/.bin/prisma
COPY --from=builder /workspace/node_modules/prisma /app/node_modules/prisma

# Copy docker scripts (entrypoint for services with Prisma migrations)
COPY docker/entrypoint-migrate.sh /app/docker/entrypoint-migrate.sh
RUN chmod +x /app/docker/entrypoint-migrate.sh

# Non-root user for security
RUN addgroup --system --gid 1001 nodejs && \
    adduser --system --uid 1001 nestjs && \
    chown -R nestjs:nodejs /app
USER nestjs

# Health check — all services expose GET /health on their HTTP port
HEALTHCHECK --interval=15s --timeout=5s --start-period=30s --retries=3 \
  CMD wget -qO- http://localhost:${PORT:-3000}/health || exit 1

CMD ["node", "main.js"]
