export const MEMBER_TOKENS = {
  MEMBER_REPOSITORY: Symbol('MEMBER_REPOSITORY'),
  BUSINESS_UNIT_REPOSITORY: Symbol('MEMBER_BUSINESS_UNIT_REPOSITORY'),
  MEMBERSHIP_REPOSITORY: Symbol('MEMBERSHIP_REPOSITORY'),
} as const;
