const { NxAppWebpackPlugin } = require('@nx/webpack/app-plugin');
const SwcTargetPlugin = require('../../swc-target-plugin');
const { join } = require('path');

module.exports = {
  output: {
    path: join(__dirname, '../../dist/apps/api-gateway'),
    clean: true,
    ...(process.env.NODE_ENV !== 'production' && {
      devtoolModuleFilenameTemplate: '[absolute-resource-path]',
    }),
  },
  plugins: [
    new NxAppWebpackPlugin({
      target: 'node',
      compiler: 'swc',
      main: './src/main.ts',
      tsConfig: './tsconfig.app.json',
      assets: ['./src/assets'],
      optimization: false,
      outputHashing: 'none',
      generatePackageJson: true,
      sourceMap: true,
      tsPluginOptions: { transpileOnly: true },
    }),
    // Patch the swc-loader rule generated by NxAppWebpackPlugin to set
    // jsc.target = 'es2022'. Without this, SWC defaults to ES5 and compiles
    // `class Foo extends Bar` into `Bar.apply(this, args)` — which throws
    // "Class constructor cannot be invoked without 'new'" for native ES6
    // classes like PrismaClient and PassportStrategy.
    new SwcTargetPlugin({ target: 'es2022' }),
  ],
};
